name: Release

on:
  push:
    tags: [ 'v*' ]
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        variant: [ 'x86_64', 'arm64', 'armv6', 'armv6_rpi' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile binary
        run: |
          mkdir -p /tmp/out
          ./crosscompile.sh ${{ matrix.variant }}
          mv go-librespot-${{ matrix.variant }} go-librespot
          tar -zcvf /tmp/out/go-librespot_${{ matrix.variant }}.tar.gz go-librespot README.md

      - name: Upload compiled binary
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.variant }}
          path: /tmp/out
          retention-days: 7

  publish:
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    steps:
      - name: Download compiled binaries
        uses: actions/download-artifact@v4
        with:
          pattern: binaries-*
          path: /tmp/out
          merge-multiple: true

      - name: Generate changelog
        uses: jaywcjlove/changelog-generator@main
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: (dependabot|renovate\\[bot\\]|dependabot\\[bot\\]|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Release binaries
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ steps.changelog.outputs.compareurl }}
            ${{ steps.changelog.outputs.changelog }}
          files: /tmp/out/*
